data("trees")
print(head(trees,10))
print(tail(trees))
print(nrow(trees))
print(ncol(trees))
print(dim(trees))
print(?trees)
print(names(trees))
print(sort(trees$Height))
print(summary(trees))
print(rownames(trees)[which.max(trees$Height)])
print(rownames(trees)[which.min(trees$Height)])
print(rownames(trees)[which.max(trees$Girth)])
print(rownames(trees)[which.min(trees$Girth)])
print(rownames(trees)[which.max(trees$Volume)])
print(rownames(trees)[which.min(trees$Volume)])
print(mean(trees$Girth))
print(mean(trees$Height))
print(mean(trees$Volume))
print(median(trees$Girth))
print(median(trees$Height))
print(median(trees$Volume))
print(quantile(trees$Girth,c(0.25)))
print(quantile(trees$Girth,c(0.75)))
print(quantile(trees$Height,c(0.25)))
print(quantile(trees$Height,c(0.75)))
print(quantile(trees$Volume,c(0.25)))
print(quantile(trees$Volume,c(0.75)))


plot(trees$Girth,trees$Height,main="Girth v/s Height",xlab="X-axis",ylab="Y-axis",col="red",cex=1,pch=15)

pie(trees$Volume,label=trees$Height,main="Pie")

hist(trees$Height,density=22,col="blue")

